kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secondary-scheduler-operator
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - secondaryschedulers.operator.openshift.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - topology.node.k8s.io
  resources:
  - noderesourcetopologies
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - services
  - serviceaccounts
  - pods
  - configmaps
  - secrets
  - namespaces
  - nodes
  - pods/eviction
  - events
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - "*"
