apiVersion: v1
kind: Pod
metadata:
  generateName: numalign-pod-
spec:
  schedulerName: topo-aware-scheduler
  containers:
  - name: numalign
    image: quay.io/fromani/numalign
    imagePullPolicy: IfNotPresent
    command: ["/usr/local/bin/numalign"]
    env:
      - name: NUMALIGN_SLEEP_HOURS
        value: "127"
    resources:
      limits:
        cpu: 1
        memory: 256Mi
      requests:
        cpu: 1
        memory: 256Mi
